{% set name = "lineax" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lineax-{{ version }}.tar.gz
  sha256: e43549a8d202432d4668afe54866741a0214ccb363487bacb2a980f72840ea48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - equinox >=0.11.5
    - jax >=0.4.26
    - jaxtyping >=0.2.20
    - typing_extensions >=4.5.0

test:
  imports:
    - lineax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/patrick-kidger/lineax
  summary: Linear solvers in JAX and Equinox.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
