{% set name = "lineax" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lineax-{{ version }}.tar.gz
  sha256: e68f1eba2f352122fdce9adc0556684f31eb8364b1a00acee484dd6e44a34e5e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - hatchling
    - pip
  run:
    - python >=3.9,<4.dev0
    - jax >=0.4.13
    - jaxtyping >=0.2.20
    - equinox >=0.11.0
    - typing-extensions >=4.5.0

test:
  imports:
    - lineax
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Linear solvers in JAX and Equinox.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
