{% set name = "lineax" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lineax-{{ version }}.tar.gz
  sha256: c3d4863ddb0595b69c19326b97c4cc2498d75a495ce8d34517ae2d7c2da459e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - hatchling
    - pip
  run:
    - python >=3.9,<4.dev0
    - jax >=0.4.26
    - jaxtyping >=0.2.20
    - equinox >=0.11.3
    - typing-extensions >=4.5.0

test:
  imports:
    - lineax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/patrick-kidger/lineax
  summary: Linear solvers in JAX and Equinox.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
