{% set name = "lineax" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lineax-{{ version }}.tar.gz
  sha256: bb2778066b8882acc88ff569d8e415bc5aa387f751b14ae262c9f9607d7f25bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - equinox >=0.11.10
    - jax >=0.4.38
    - jaxtyping >=0.2.24
    - typing_extensions >=4.5.0

test:
  imports:
    - lineax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/patrick-kidger/lineax
  summary: Linear solvers in JAX and Equinox.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
